### ISSUE TITLE
Any example roms?

### ISSUE THREAD

**Issue by miratcan** [mborgbrant/c64js#1]
It would be good if there was any roms to load.

**Comment by mborgbrant** [comment]
Hi!
The emulator can run a couple of roms. You have drop them in .prg format at
the emulators canvas.
Due to the lack of details in the graphics emulator there are only a few
roms which is actually working.

Try this: http://sos.gd/flappy64/

This project is just in a very early stage, but I hope I will get more help
to finish it now when its public.

Bet regards,
mikael

söndag 3 april 2016 skrev Mirat Can Bayrak notifications@github.com:

**Comment by miratcan** [comment]
Very good job, thanks :+1:
